### ISSUE TITLE
env file missing

### ISSUE THREAD

**Issue by zer0init1** [aasaam/apt-cacher-ng#1]
Build stops because one of the files is missing

```
root@218497:/opt/apt-cacher-ng# docker compose up -d
open /opt/apt-cacher-ng/env: no such file or directory
```

File ls
```
root@server:/opt/apt-cacher-ng# ls -la *env*
ls: cannot access '*env*': No such file or directory
root@218497:/opt/apt-cacher-ng#
```

Git info
```
root@server:/opt/apt-cacher-ng# git log --name-status HEAD^..HEAD
commit 8b0b48d95d8314983990bf2e87e74678d343b88e (HEAD -> master, origin/master, origin/HEAD)
Author: Muhammad Hussein Fattahizadeh <m@mhf.ir>
Date:   Sun Jul 17 11:44:58 2022 +0430

    feat: add bind address
```

**Comment by mhf-ir** [comment]
you can simple add .env file for your application.
```bash
touch .env
# or 
echo "ENVNAME=ValueForApp" > .env
```

then start the container.

It's best practice to git ignore `.env` file

[Should I add .env to .gitignore?](https://salferrarello.com/add-env-to-gitignore/)

**Comment by zer0init1** [comment]
This is not a problem for me. I just pointed out that the build is not possible because this file is not in the repository right now.

Maybe you should add an empty file so other users don't have problems with launching it right away? ;)

**Comment by mhf-ir** [comment]
First, this repo automatically build using GitHub action so there is no build task. just pull and run the image.

In most cases `.env` file must not be part of git repo . https://stackoverflow.com/questions/43664565/why-do-people-put-the-env-into-gitignore

there is serveral way to handle this problem.
1. simply add .env file during `docker-compose up` as i describe before.
2. comment `env_file` directive in https://github.com/aasaam/apt-cacher-ng/blob/master/docker-compose.yml#L8
?

what's your suggestion?

**Comment by zer0init1** [comment]
I have known about `.env` best practice ;)

I would choose the second option and then anyone who uses your repository would have no problems at all and everything would start from 1 command ;)

Since it is not an error in the code / configuration - I think we can close this issue.
